name: Testing Iterators exercise

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install --only=prod
    - name: Run jest
      run: |
        npx http-server --silent --port 8080 &
        npx jest __tests__/test_part3.js --color=true
